# Configuration cargo-audit pour xsshend
# https://github.com/RustSec/cargo-audit

[advisories]
# Vulnérabilités connues et acceptées avec justification
ignore = [
    "RUSTSEC-2023-0071",  # rsa crate - Marvin Attack (pas de solution disponible)
]

[output]
# Format de sortie
format = "terminal"
# Niveau de verbosité
quiet = false
# Montrer les statistiques
show_tree = true

[yanked]
# Ignorer les crates yanked (retirées)
ignore = []