[package]
name = "xsshend"
version = "0.1.0"
edition = "2024"
description = "Outil Rust de téléversement multi-SSH avec interface TUI"
license = "MIT"
authors = ["William <william@example.com>"]
repository = "https://github.com/username/xsshend"

[dependencies]
# SSH & Transferts
ssh2 = "0.9"

# Interface utilisateur
indicatif = "0.17"
dialoguer = "0.11"
console = "0.15"
crossterm = "0.27"

# CLI & Configuration
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Parallélisation
rayon = "1.8"

# Sécurité
rpassword = "7.3"
dirs = "5.0"

# Utilitaires
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.8"
