name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:  # Permet de déclencher manuellement

permissions:
  contents: write
  pages: write
  id-token: write

# Empêcher les déploiements simultanés de documentation
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-docs:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages (via gh-pages branch)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: true
        cname: # Optionnel: votre domaine custom